### ISSUE TITLE
about theme images

### ISSUE THREAD

**Issue by jaronromach** [Mahrjose/NyxDE#1]
bro your project is great. i just wanna tell you something. please DO NOT put everywhere anime-shits images, themes or something like everyone did. be different and serious. Project is so god btw !

TLDR: anime theming is so bad everyone is bored. everyone on unixporn doin anime-hentai rice's and thats cringe AF

edit: after u saw this comment, u cant delete it bro.

**Comment by jaronromach** [comment]
edit: after u saw this comment, u cant delete it bro.

**Comment by Mahrjose** [comment]
Thank you man!!
will keep in mind that about anime 😂 😂

**Comment by Mahrjose** [comment]
Thank you man!!
will keep in mind that about anime 😂 😂
